### ISSUE TITLE
EADDRINUSE error when starting debug

### ISSUE THREAD

**Issue by michaelkutuzov** [TheBenji/brackets-node-debugger#18]
When I try to use debugger I have error what is shown below.
![2016-11-18_20-51-45](https://cloud.githubusercontent.com/assets/20220032/20440362/dbc22d5a-add0-11e6-8982-6534bf7bfc3a.png)

First of all I try to  change port in brackets.json, but independent from number in config file error is still about port 5858.

Then I check what is running on port 5858. This is node.js)
Is it a bug or a feature?
![2016-11-18_20-56-21](https://cloud.githubusercontent.com/assets/20220032/20440566/ba4b11ea-add1-11e6-86da-3e8f7c7163a0.png)
If it is bug how can i fix it?
Thanks

**Comment by TheBenji** [comment]
I don't actively maintain this project anymore so not too sure.
If you still have this issue maybe double check whether there are more than one node(debugger) processes running but as I said, didn't even check if it's still works at all with current node version - might be just broken to be honest.
